[package]
name = "starknet-cxx"
version = "0.1.0"
authors = ["Jonathan LEI <me@xjonathan.dev>"]
edition = "2021"

[dependencies]
cxx = "1.0"

# Using path dependency here to make development easier. However, you probably want to fetch the
# crate from GitHub instead (because the `scfx-starknet-core` crate isn't being published to crates.io
# regularly like `scfx-starknet-crypto` at the moment), which means changing the next line to:
#
# scfx-starknet-core = { git = "https://github.com/xJonathanLEI/starknet-rs" }
scfx-starknet-core = { path = "../../../scfx-starknet-core" }

# Same as above.
# 
# This entry is needed to enable the `signature-display` feature of `scfx-starknet-crypto`.
scfx-starknet-crypto = { path = "../../../scfx-starknet-crypto", default-features = false, features = ["signature-display"] }

[build-dependencies]
cxx-build = "1.0"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
